### ISSUE TITLE
whats this library?

### ISSUE THREAD

**Issue by pishguy** [osamaasifoak/flutter_cart#2]

**Comment by osamaasifoak** [comment]
Hi, @MahdiPishguy Hope you are doing fine. Actually, this package is created for shopping cart maintenance. This package helps you a lot while working on an e-commerce platform because it provides you a lot of features like add to cart and remove items from cart etc. We are working on it to make this package more helpful. If you still have any questions you may ask. 
Thank you.

**Comment by pishguy** [comment]
@osamaasifoak  thank you very much bro. home you are doing fine too :) 

and thanks reply to my question, i don't have question now, but i like to use the library in our project ;)
